# Generated by Django 4.1.2 on 2022-11-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "charging_unit_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userentity",
                    ),
                ),
            ],
            options={
                "db_table": "reservation",
            },
        ),
        migrations.CreateModel(
            name="ChargingUnitEntity",
            fields=[
                (
                    "charging_unit_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(default="", max_length=255)),
                ("brand", models.TextField(default="", max_length=32)),
                ("model", models.TextField(default="", max_length=32)),
                ("address", models.TextField(max_length=128)),
                ("occupied_slots", models.IntegerField(default=0)),
                ("max_slots", models.IntegerField()),
                ("location", models.CharField(editable=False, max_length=32)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userentity",
                    ),
                ),
            ],
            options={
                "db_table": "charging_unit",
            },
        ),
    ]
