# Generated by Django 4.1.2 on 2022-11-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_unit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingunitentity",
            name="location",
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
