# Generated by Django 4.1.2 on 2022-11-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charging_unit", "0002_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chargingunitentity",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="chargingunitentity",
            name="lng",
        ),
    ]
