# Generated by Django 4.1.2 on 2022-11-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_unit", "0003_remove_chargingunitentity_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingunitentity",
            name="location",
            field=models.TextField(blank=True, default={}, null=True),
        ),
        migrations.AlterModelTable(
            name="reservation",
            table="reservation",
        ),
    ]
