# Generated by Django 4.1.2 on 2022-11-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charging_unit", "0004_chargingunitentity_location_alter_reservation_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chargingunitentity",
            old_name="location",
            new_name="_location",
        ),
    ]
