# Generated by Django 4.1.2 on 2022-11-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charging_unit", "0005_rename_location_chargingunitentity__location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chargingunitentity",
            name="_location",
        ),
    ]
